# Generated by Django 2.0.1 on 2018-02-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='phase',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Crescendo'), (2, 'Avaliando'), (3, 'Agindo'), (2, 'Feito')]),
        ),
        migrations.DeleteModel(
            name='Phase',
        ),
    ]
