# Generated by Django 2.0.1 on 2018-02-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
