# Generated by Django 2.0.1 on 2018-02-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0002_auto_20180221_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='phase',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Crescendo')]),
        ),
    ]
