# Generated by Django 2.0.1 on 2018-03-07 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideax', '0003_auto_20180225_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('key_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Phase_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_phase', models.PositiveSmallIntegerField()),
                ('previous_phase', models.PositiveSmallIntegerField()),
                ('date_change', models.DateTimeField(verbose_name='data da mudança')),
                ('current', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='idea',
            name='phase',
        ),
        migrations.AddField(
            model_name='idea',
            name='discarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phase_history',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideax.Idea'),
        ),
        migrations.AddField(
            model_name='idea',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ideax.Category'),
        ),
    ]
