# Generated by Django 2.0.1 on 2018-03-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0004_auto_20180307_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discarded',
            field=models.BooleanField(default=False),
        ),
    ]
