# Generated by Django 2.0.1 on 2018-03-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='key_word',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='description',
        ),
        migrations.AddField(
            model_name='idea',
            name='oportunity',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='solution',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='target',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
