# Generated by Django 2.0.1 on 2018-03-29 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideax', '0007_auto_20180328_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_term_accept', models.NullBooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ideax.UserProfile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='raw_comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='idea',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideax.UserProfile'),
        ),
        migrations.AlterField(
            model_name='phase_history',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ideax.UserProfile'),
        ),
        migrations.AlterField(
            model_name='popular_vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ideax.UserProfile'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ideax.UserProfile'),
        ),
    ]
