# Generated by Django 2.0.1 on 2018-04-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0008_auto_20180329_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='manager',
            field=models.NullBooleanField(default=False),
        ),
    ]
