# Generated by Django 2.0.1 on 2018-04-13 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0009_userprofile_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('weight', models.IntegerField()),
                ('init_date', models.DateTimeField()),
                ('final_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateTimeField()),
                ('dimension_value', models.IntegerField()),
                ('category_dimension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ideax.Category_Dimension')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ideax.Dimension')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ideax.Idea')),
                ('valuator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ideax.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='category_dimension',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ideax.Dimension'),
        ),
    ]
