# Generated by Django 2.0.1 on 2018-05-07 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0014_auto_20180503_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Use_Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.TextField(max_length=12500)),
                ('init_date', models.DateTimeField()),
                ('final_date', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ideax.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='idea',
            name='category_image',
            field=models.CharField(default='/media/category/default.png', max_length=200),
        ),
    ]
